# Generated by Django 5.2.1 on 2025-06-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stimme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fach', models.CharField(max_length=100)),
                ('abgegeben_am', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
